class @Probabilities(@batterPower, @batterContact, @pitcher)

  constructor: ->
    @pitchBall = null
    @pitchStrike = null
    @contactFoul = null
    @contactSingle = null
    @contactDouble = null
    @contactTriple = null
    @contactHomeRun = null
    @contactPopFlyOut = null

  PITCH_BALL_PROB_LEVEL_1 = 30
  PITCH_STRIKE_PROB_LEVEL_1 = 15
  PITCH_CONTACT_PROB_LEVEL_1 = 100 - PITCH_BALL_PROB - PITCH_STRIKE_PROB

  PITCH_BALL_PROB_LEVEL_2 = 25
  PITCH_STRIKE_PROB_LEVEL_2 = 20
  PITCH_CONTACT_PROB_LEVEL_2 = 100 - PITCH_BALL_PROB - PITCH_STRIKE_PROB

  PITCH_BALL_PROB_LEVEL_3 = 20
  PITCH_STRIKE_PROB_LEVEL_3 = 25
  PITCH_CONTACT_PROB_LEVEL_3 = 100 - PITCH_BALL_PROB - PITCH_STRIKE_PROB

  PITCH_BALL_PROB_LEVEL_4 = 18
  PITCH_STRIKE_PROB_LEVEL_4 = 35
  PITCH_CONTACT_PROB_LEVEL_4 = 100 - PITCH_BALL_PROB - PITCH_STRIKE_PROB

  PITCH_BALL_PROB_LEVEL_5 = 15
  PITCH_STRIKE_PROB_LEVEL_5 = 40
  PITCH_CONTACT_PROB_LEVEL_5 = 100 - PITCH_BALL_PROB - PITCH_STRIKE_PROB

  PITCH_BALL_PROB_LEVEL_6 = 13
  PITCH_STRIKE_PROB_LEVEL_6 = 45
  PITCH_CONTACT_PROB_LEVEL_6 = 100 - PITCH_BALL_PROB - PITCH_STRIKE_PROB

  PITCH_BALL_PROB_LEVEL_7 = 11
  PITCH_STRIKE_PROB_LEVEL_7 = 50
  PITCH_CONTACT_PROB_LEVEL_7 = 100 - PITCH_BALL_PROB - PITCH_STRIKE_PROB

  PITCH_BALL_PROB_LEVEL_8 = 10
  PITCH_STRIKE_PROB_LEVEL_8 = 55
  PITCH_CONTACT_PROB_LEVEL_8 = 100 - PITCH_BALL_PROB - PITCH_STRIKE_PROB

  PITCH_BALL_PROB_LEVEL_9 = 8
  PITCH_STRIKE_PROB_LEVEL_9 = 62
  PITCH_CONTACT_PROB_LEVEL_9 = 100 - PITCH_BALL_PROB - PITCH_STRIKE_PROB

  CONTACT_FOUL_PROB_LEVEL_1 = 35
  CONTACT_SINGLE_PROB_LEVEL_1 = 5
  CONTACT_DOUBLE_PROB_LEVEL_1 = 3
  CONTACT_TRIPLE_PROB_LEVEL_1 = 1
  CONTACT_HOME_RUN_PROB_LEVEL_1 = 1
  CONTACT_POP_FLY_OUT_PROB_LEVEL_1 = 30
  CONTACT_GROUND_BALL_OUT_PROB_LEVEL_1 = 25

  CONTACT_FOUL_PROB_LEVEL_2 = 35
  CONTACT_SINGLE_PROB_LEVEL_2 = 8
  CONTACT_DOUBLE_PROB_LEVEL_2 = 5
  CONTACT_TRIPLE_PROB_LEVEL_2 = 1
  CONTACT_HOME_RUN_PROB_LEVEL_2 = 4
  CONTACT_POP_FLY_OUT_PROB_LEVEL_2 = 22
  CONTACT_GROUND_BALL_OUT_PROB_LEVEL_2 = 23

  CONTACT_FOUL_PROB_LEVEL_3 = 35
  CONTACT_SINGLE_PROB_LEVEL_3 = 15
  CONTACT_DOUBLE_PROB_LEVEL_3 = 5
  CONTACT_TRIPLE_PROB_LEVEL_3 = 1
  CONTACT_HOME_RUN_PROB_LEVEL_3 = 4
  CONTACT_POP_FLY_OUT_PROB_LEVEL_3 = 20
  CONTACT_GROUND_BALL_OUT_PROB_LEVEL_3 = 20

  CONTACT_FOUL_PROB_LEVEL_4 = 35
  CONTACT_SINGLE_PROB_LEVEL_4 = 20
  CONTACT_DOUBLE_PROB_LEVEL_4 = 8
  CONTACT_TRIPLE_PROB_LEVEL_4 = 2
  CONTACT_HOME_RUN_PROB_LEVEL_4 = 5
  CONTACT_POP_FLY_OUT_PROB_LEVEL_4 = 15
  CONTACT_GROUND_BALL_OUT_PROB_LEVEL_4 = 15

  CONTACT_FOUL_PROB_LEVEL_5 = 35
  CONTACT_SINGLE_PROB_LEVEL_5 = 25
  CONTACT_DOUBLE_PROB_LEVEL_5 = 10
  CONTACT_TRIPLE_PROB_LEVEL_5 = 5
  CONTACT_HOME_RUN_PROB_LEVEL_5 = 10
  CONTACT_POP_FLY_OUT_PROB_LEVEL_5 = 8
  CONTACT_GROUND_BALL_OUT_PROB_LEVEL_5 = 7
